# Generated by Django 4.2.4 on 2024-05-07 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_homework_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(default=datetime.date(2024, 5, 7), verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mark'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(choices=[('nothing', 'выдано'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='nothing', max_length=50, verbose_name='Оценка'),
        ),
    ]
