# Generated by Django 4.2.4 on 2024-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_homework_date_alter_homework_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
    ]
