# Generated by Django 4.2.4 on 2024-05-25 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homework_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=250, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(default='email', max_length=50, verbose_name='Электронная почта')),
                ('login', models.CharField(default='login', max_length=150, verbose_name='Логин')),
                ('password', models.CharField(default='password', max_length=150, verbose_name='Пароль')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администратор',
            },
        ),
    ]
