# Generated by Django 4.2.4 on 2024-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lesson_name_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
