# Generated by Django 4.2.4 on 2024-05-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='files', verbose_name='Файл'),
        ),
    ]
