# Generated by Django 4.2.4 on 2024-05-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lesson_description_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files', verbose_name='Файл'),
        ),
    ]
