# Generated by Django 4.2.4 on 2024-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mark_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(choices=[('выдано', 'выдано'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='nothing', max_length=50, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
